export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CURRENT_USER_LOADING = "CURRENT_USER_LOADING";
export const CLEAR_USER_LOADING = "CLEAR_USER_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER = "GET_ORDER";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHECKOUT_LOADING = "CHECKOUT_LOADING";
export const DELETE_CART_ITEMS = "DELETE_CART_ITEMS";
export const CHECKOUT_LOADING_CLEAR = "CHECKOUT_LOADING_CLEAR";
